/**
 * @fileoverview Behavioral parity tests for Lingo folder: 01
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 01 (zee_intro).
 */

const { LingoContract, createMockContext } = require('./helpers');

describe('01 Lingo behavioral parity', () => {
  describe('BehaviorScript 11 - BuffaBH', () => {
    describe('Stopped', () => {
      // Buffa animation state-machine: mode selects animation chart.
      // No modeled transitions — purely visual/animation state changes.
      const branches = [
        {
          conditions: [{ type: 'other', key: 'mode_eq_WalkRightStart', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_WalkRight', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'random_2_gt_1', negated: false }],
              actions: [],
              children: [],
              elseBranch: {
                conditions: [],
                actions: [],
                children: [
                  {
                    conditions: [{ type: 'other', key: 'locH_lt_rightBorder', negated: false }],
                    actions: [],
                    children: [],
                    elseBranch: null,
                  },
                ],
                elseBranch: null,
              },
            },
          ],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_WalkRightStop', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_WalkLeftStart', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_WalkLeft', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'random_2_gt_1', negated: false }],
              actions: [],
              children: [],
              elseBranch: {
                conditions: [],
                actions: [],
                children: [
                  {
                    conditions: [{ type: 'other', key: 'locH_gt_leftBorder', negated: false }],
                    actions: [],
                    children: [],
                    elseBranch: null,
                  },
                ],
                elseBranch: null,
              },
            },
          ],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_WalkLeftStop', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_GetDown', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'mode_eq_Sleep', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'random_30_eq_1', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the mode of nil = #WalkRightStart)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkRightStart: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: (the mode of nil = #WalkRight), (random(2) > 1)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkRight: true, random_2_gt_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: (the mode of nil = #WalkRight), NOT (random(2) > 1), the locH of (sprite SP < rightBorder)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkRight: true, random_2_gt_1: false, locH_lt_rightBorder: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: (the mode of nil = #WalkRight), NOT (random(2) > 1), NOT the locH of (sprite SP < rightBorder)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkRight: true, random_2_gt_1: false, locH_lt_rightBorder: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: (the mode of nil = #WalkRightStop)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkRightStop: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: (the mode of nil = #WalkLeftStart)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkLeftStart: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: (the mode of nil = #WalkLeft), (random(2) > 1)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkLeft: true, random_2_gt_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 8: (the mode of nil = #WalkLeft), NOT (random(2) > 1), the locH of (sprite SP > leftBorder)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkLeft: true, random_2_gt_1: false, locH_gt_leftBorder: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 9: (the mode of nil = #WalkLeft), NOT (random(2) > 1), NOT the locH of (sprite SP > leftBorder)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkLeft: true, random_2_gt_1: false, locH_gt_leftBorder: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 10: (the mode of nil = #WalkLeftStop)', () => {
        const ctx = createMockContext({ other: { mode_eq_WalkLeftStop: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 11: (the mode of nil = #GetDown)', () => {
        const ctx = createMockContext({ other: { mode_eq_GetDown: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 12: (the mode of nil = #Sleep), (random(30) = 1)', () => {
        const ctx = createMockContext({ other: { mode_eq_Sleep: true, random_30_eq_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 13: (the mode of nil = #Sleep), NOT (random(30) = 1)', () => {
        const ctx = createMockContext({ other: { mode_eq_Sleep: true, random_30_eq_1: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 14: the mode of nil = otherwise', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'BuffaFreezed', negated: true }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'random_100_eq_1', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: null,
                },
              ],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: NOT BuffaFreezed, (the mode of nil = #Wait), (random(100) = 1)', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: true, mode_eq_Wait: true, random_100_eq_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: NOT BuffaFreezed, (the mode of nil = #Wait), NOT (random(100) = 1)', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: true, mode_eq_Wait: true, random_100_eq_1: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: NOT BuffaFreezed', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: true, mode_eq_Wait: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: BuffaFreezed', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('mouseUp', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'BuffaFreezed', negated: true }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait', negated: false }],
              actions: [],
              children: [],
              elseBranch: {
                conditions: [],
                actions: [],
                children: [
                  {
                    conditions: [{ type: 'other', key: 'mode_eq_Sleep', negated: false }],
                    actions: [],
                    children: [],
                    elseBranch: null,
                  },
                ],
                elseBranch: null,
              },
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: NOT BuffaFreezed, (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: true, mode_eq_Wait: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: NOT BuffaFreezed, NOT (mode = #Wait), (mode = #Sleep)', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: true, mode_eq_Wait: false, mode_eq_Sleep: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: NOT BuffaFreezed, NOT (mode = #Wait), NOT (mode = #Sleep)', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: true, mode_eq_Wait: false, mode_eq_Sleep: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: BuffaFreezed', () => {
        const ctx = createMockContext({ other: { BuffaFreezed: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 11 - BuffaBH', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

  describe('BehaviorScript 15 - MulleShipyBH', () => {
    describe('Stopped', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'mode_eq_Talk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'currentAnimChart_eq_TalkToMe', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the mode of nil = #Talk), (currentAnimChart = #TalkToMe)', () => {
        const ctx = createMockContext({ other: { mode_eq_Talk: true, currentAnimChart_eq_TalkToMe: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: (the mode of nil = #Talk), NOT (currentAnimChart = #TalkToMe)', () => {
        const ctx = createMockContext({ other: { mode_eq_Talk: true, currentAnimChart_eq_TalkToMe: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: the mode of nil = otherwise', () => {
        const ctx = createMockContext({ other: { mode_eq_Talk: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('makeMulleTalk', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'argAction_eq_NormalTalk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'random_2_eq_1', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: null,
                },
              ],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'argAction_eq_InfoTalk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'argAction_eq_PrioTalk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait_or_Talk', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the argAction of nil = #NormalTalk), (mode = #Wait), (random(2) = 1)', () => {
        const ctx = createMockContext({ other: { argAction_eq_NormalTalk: true, mode_eq_Wait: true, random_2_eq_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: (the argAction of nil = #NormalTalk), (mode = #Wait), NOT (random(2) = 1)', () => {
        const ctx = createMockContext({ other: { argAction_eq_NormalTalk: true, mode_eq_Wait: true, random_2_eq_1: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: (the argAction of nil = #NormalTalk), NOT (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { argAction_eq_NormalTalk: true, mode_eq_Wait: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: (the argAction of nil = #InfoTalk), (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { argAction_eq_InfoTalk: true, mode_eq_Wait: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: (the argAction of nil = #InfoTalk), NOT (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { argAction_eq_InfoTalk: true, mode_eq_Wait: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: (the argAction of nil = #PrioTalk), ((mode = #Wait) OR (mode = #Talk))', () => {
        const ctx = createMockContext({ other: { argAction_eq_PrioTalk: true, mode_eq_Wait_or_Talk: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: (the argAction of nil = #PrioTalk), ((mode = #Wait) OR (mode = #Talk))', () => {
        const ctx = createMockContext({ other: { argAction_eq_PrioTalk: true, mode_eq_Wait_or_Talk: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 15 - MulleShipyBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

  describe('BehaviorScript 3', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'soundBusy_1', negated: false }],
          actions: [{ type: 'goFrame' }],
          children: [],
          elseBranch: {
            conditions: [],
            actions: [{ type: 'go', target: '04' }],
            children: [],
            elseBranch: null,
          },
        },
      ];

      test('path 1: soundBusy(1) → go(the frame)', () => {
        const ctx = createMockContext({ other: { soundBusy_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 3', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });

      test('path 2: NOT soundBusy(1) → go(1, "04")', () => {
        const ctx = createMockContext({ other: { soundBusy_1: false } });
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 3', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('04');
      });

    });

  });

  describe('BehaviorScript 5', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '15' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "15")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/01/BehaviorScript 5', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('15');
      });

    });

  });

  describe('ParentScript 4 - Dir', () => {
    describe('init', () => {
      // All paths call setSky and drawBoat — runtime rendering calls.
      // The machineType/getType conditions control layout but all converge.
      const branches = [
        {
          conditions: [{ type: 'other', key: 'machineType_neq_256', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'getType_eq_1', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
            {
              conditions: [{ type: 'other', key: 'getType_eq_2', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
            {
              conditions: [{ type: 'other', key: 'getType_eq_3', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
            {
              conditions: [{ type: 'other', key: 'getType_eq_4', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the machineType <> 256), (the getType of nil = 1) → setSky(the weather of gMulleGlobals), drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { machineType_neq_256: true, getType_eq_1: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: (the machineType <> 256), (the getType of nil = 2) → setSky(the weather of gMulleGlobals), drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { machineType_neq_256: true, getType_eq_2: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: (the machineType <> 256), (the getType of nil = 3) → setSky(the weather of gMulleGlobals), drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { machineType_neq_256: true, getType_eq_3: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: (the machineType <> 256), (the getType of nil = 4) → setSky(the weather of gMulleGlobals), drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { machineType_neq_256: true, getType_eq_4: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: (the machineType <> 256) → setSky(the weather of gMulleGlobals), drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { machineType_neq_256: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: NOT (the machineType <> 256) → setSky(the weather of gMulleGlobals), drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { machineType_neq_256: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('loop', () => {
      // Dialog state-machine: OKToTalk/dialogClosed gate, loopCounter,
      // FirstTime/secondTime control dialog selection. No modeled transitions.
      const branches = [
        {
          conditions: [{ type: 'other', key: 'OKToTalk_AND_dialogClosed', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'loopCounter_gt_0', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
                  actions: [],
                  children: [
                    {
                      conditions: [{ type: 'other', key: 'loopCounter_eq_0', negated: false }],
                      actions: [],
                      children: [
                        {
                          conditions: [{ type: 'other', key: 'count_firstDialogList_gt_0', negated: false }],
                          actions: [],
                          children: [],
                          elseBranch: null,
                        },
                      ],
                      elseBranch: null,
                    },
                  ],
                  elseBranch: {
                    conditions: [],
                    actions: [],
                    children: [
                      {
                        conditions: [{ type: 'other', key: 'secondTime', negated: false }],
                        actions: [],
                        children: [
                          {
                            conditions: [{ type: 'other', key: 'loopCounter_eq_0', negated: false }],
                            actions: [],
                            children: [],
                            elseBranch: null,
                          },
                        ],
                        elseBranch: {
                          conditions: [],
                          actions: [],
                          children: [
                            {
                              conditions: [{ type: 'other', key: 'loopCounter_eq_0', negated: false }],
                              actions: [],
                              children: [],
                              elseBranch: null,
                            },
                          ],
                          elseBranch: null,
                        },
                      },
                    ],
                    elseBranch: null,
                  },
                },
              ],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: OKToTalk AND dialogClosed, (loopCounter > 0), FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: true, loopCounter_eq_0: true, count_firstDialogList_gt_0: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: OKToTalk AND dialogClosed, (loopCounter > 0), FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: true, loopCounter_eq_0: true, count_firstDialogList_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: OKToTalk AND dialogClosed, (loopCounter > 0), FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: true, loopCounter_eq_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: OKToTalk AND dialogClosed, (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: false, secondTime: true, loopCounter_eq_0: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: OKToTalk AND dialogClosed, (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: false, secondTime: true, loopCounter_eq_0: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: OKToTalk AND dialogClosed, (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: false, secondTime: true, loopCounter_eq_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: OKToTalk AND dialogClosed, (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: false, secondTime: false, loopCounter_eq_0: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 8: OKToTalk AND dialogClosed, (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: false, secondTime: false, loopCounter_eq_0: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 9: OKToTalk AND dialogClosed, (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, FirstTime: false, secondTime: false, loopCounter_eq_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 10: OKToTalk AND dialogClosed, NOT (loopCounter > 0), FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 11: OKToTalk AND dialogClosed, NOT (loopCounter > 0), FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 12: OKToTalk AND dialogClosed, NOT (loopCounter > 0), FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 13: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 14: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 15: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 16: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 17: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 18: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 19: OKToTalk AND dialogClosed', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('mouse', () => {
      // Wood, Metal, and Quay are checked sequentially (siblings).
      // Wood/Metal trigger drawBoat (not modeled); Quay triggers go("Quay").
      const branches = [
        {
          conditions: [{ type: 'other', key: 'argWhat_eq_click', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'hull_neq_NoHull', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'dragToWhere_eq_Wood', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: null,
                },
                {
                  conditions: [{ type: 'other', key: 'dragToWhere_eq_Metal', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: null,
                },
                {
                  conditions: [{ type: 'other', key: 'dragToWhere_eq_Quay', negated: false }],
                  actions: [{ type: 'go', target: 'Quay' }],
                  children: [],
                  elseBranch: null,
                },
              ],
              elseBranch: {
                conditions: [],
                actions: [],
                children: [
                  {
                    conditions: [{ type: 'other', key: 'dragToWhere_eq_Quay', negated: false }],
                    actions: [],
                    children: [],
                    elseBranch: null,
                  },
                ],
                elseBranch: null,
              },
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., the dragToWhere of (argObj = #Wood) → drawBoat(drawOffset, VOID, VOID, 0), drawBoat(drawOffset, ...', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: true, dragToWhere_eq_Metal: true, dragToWhere_eq_Quay: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('Quay');
      });

      test('path 2: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., the dragToWhere of (argObj = #Wood) → drawBoat(drawOffset, VOID, VOID, 0), drawBoat(drawOffset, ...', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: true, dragToWhere_eq_Metal: true, dragToWhere_eq_Quay: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., the dragToWhere of (argObj = #Wood) → drawBoat(drawOffset, VOID, VOID, 0), go("Quay")', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: true, dragToWhere_eq_Metal: false, dragToWhere_eq_Quay: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('Quay');
      });

      test('path 4: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., the dragToWhere of (argObj = #Wood) → drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: true, dragToWhere_eq_Metal: false, dragToWhere_eq_Quay: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., NOT the dragToWhere of (argObj = #Wood) → drawBoat(drawOffset, VOID, VOID, 0), go("Quay")', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: false, dragToWhere_eq_Metal: true, dragToWhere_eq_Quay: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('Quay');
      });

      test('path 6: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., NOT the dragToWhere of (argObj = #Wood) → drawBoat(drawOffset, VOID, VOID, 0)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: false, dragToWhere_eq_Metal: true, dragToWhere_eq_Quay: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., NOT the dragToWhere of (argObj = #Wood) → go("Quay")', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: false, dragToWhere_eq_Metal: false, dragToWhere_eq_Quay: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('Quay');
      });

      test('path 8: (the argWhat of nil = #click), NOT (getCurrentHull(the boatViewHandler of gMulleGlobals)..., NOT the dragToWhere of (argObj = #Wood)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: true, dragToWhere_eq_Wood: false, dragToWhere_eq_Metal: false, dragToWhere_eq_Quay: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 9: (the argWhat of nil = #click), (getCurrentHull(the boatViewHandler of gMulleGlobals) = #..., the dragToWhere of (argObj = #Quay)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: false, dragToWhere_eq_Quay: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 10: (the argWhat of nil = #click), (getCurrentHull(the boatViewHandler of gMulleGlobals) = #..., NOT the dragToWhere of (argObj = #Quay)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, hull_neq_NoHull: false, dragToWhere_eq_Quay: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('new', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'isItTheVeryFirstTime', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'not_voidp_FirstTime', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: {
                    conditions: [],
                    actions: [],
                    children: [
                      {
                        conditions: [{ type: 'other', key: 'not_voidp_secondTime', negated: false }],
                        actions: [],
                        children: [
                          {
                            conditions: [{ type: 'other', key: 'secondTime_AND_hull_neq_NoHull', negated: false }],
                            actions: [],
                            children: [],
                            elseBranch: null,
                          },
                        ],
                        elseBranch: null,
                      },
                    ],
                    elseBranch: null,
                  },
                },
              ],
              elseBranch: null,
            },
          ],
          elseBranch: {
            conditions: [],
            actions: [],
            children: [
              {
                conditions: [{ type: 'other', key: 'not_voidp_FirstTime', negated: false }],
                actions: [],
                children: [
                  {
                    conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
                    actions: [],
                    children: [],
                    elseBranch: {
                      conditions: [],
                      actions: [],
                      children: [
                        {
                          conditions: [{ type: 'other', key: 'not_voidp_secondTime', negated: false }],
                          actions: [],
                          children: [
                            {
                              conditions: [{ type: 'other', key: 'secondTime_AND_hull_neq_NoHull', negated: false }],
                              actions: [],
                              children: [],
                              elseBranch: null,
                            },
                          ],
                          elseBranch: null,
                        },
                      ],
                      elseBranch: null,
                    },
                  },
                ],
                elseBranch: null,
              },
            ],
            elseBranch: null,
          },
        },
      ];

      test('path 1: isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: true, not_voidp_FirstTime: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: true, not_voidp_FirstTime: true, FirstTime: false, not_voidp_secondTime: true, secondTime_AND_hull_neq_NoHull: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: true, not_voidp_FirstTime: true, FirstTime: false, not_voidp_secondTime: true, secondTime_AND_hull_neq_NoHull: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: true, not_voidp_FirstTime: true, FirstTime: false, not_voidp_secondTime: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: isItTheVeryFirstTime(the user of gMulleGlobals), voidp(FirstTime)', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: true, not_voidp_FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: NOT isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: false, not_voidp_FirstTime: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: NOT isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: false, not_voidp_FirstTime: true, FirstTime: false, not_voidp_secondTime: true, secondTime_AND_hull_neq_NoHull: true } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 8: NOT isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: false, not_voidp_FirstTime: true, FirstTime: false, not_voidp_secondTime: true, secondTime_AND_hull_neq_NoHull: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 9: NOT isItTheVeryFirstTime(the user of gMulleGlobals), NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: false, not_voidp_FirstTime: true, FirstTime: false, not_voidp_secondTime: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 10: NOT isItTheVeryFirstTime(the user of gMulleGlobals), voidp(FirstTime)', () => {
        const ctx = createMockContext({ other: { isItTheVeryFirstTime: false, not_voidp_FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/01/ParentScript 4 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

});
