/**
 * @fileoverview Behavioral parity tests for Lingo folder: 02
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 02.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/02/02/casts/Internal/ParentScript 10 - Dir.ls
// Pattern: simple_transition
describe('ParentScript 10 - Dir.ls → mouse', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'argWhat____click', negated: false }],
      actions: [{ type: 'go', target: 'NewShelf' }, { type: 'go', target: 'NewShelf' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: argWhat = #click', () => {
    const ctx = createMockContext({ other: { argWhat____click: true } });
    const contract = new LingoContract('decompiled_lingo/02/02/casts/Internal/ParentScript 10 - Dir.ls', 'mouse', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('NewShelf');
    expect(result.transition).toBe('NewShelf');
  });

});
