/**
 * @fileoverview Behavioral parity tests for Lingo folder: 11
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 11.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/11/11/casts/Internal/BehaviorScript 78 - MulleLogBH.ls
// Pattern: simple_transition
describe('BehaviorScript 78 - MulleLogBH.ls → WarnOfThrowing', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'not__whichFrame____Talk_', negated: true }],
      actions: [{ type: 'go', target: 'Wait' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: not (whichFrame = #Talk)', () => {
    const ctx = createMockContext({ other: { not__whichFrame____Talk_: false } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/BehaviorScript 78 - MulleLogBH.ls', 'WarnOfThrowing', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Wait');
  });

});

// Source: decompiled_lingo/11/11/casts/Internal/BehaviorScript 78 - MulleLogBH.ls
// Pattern: simple_transition
describe('BehaviorScript 78 - MulleLogBH.ls → fullAlert', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'not__whichFrame____Talk_', negated: true }],
      actions: [{ type: 'go', target: 'Wait' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: not (whichFrame = #Talk)', () => {
    const ctx = createMockContext({ other: { not__whichFrame____Talk_: false } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/BehaviorScript 78 - MulleLogBH.ls', 'fullAlert', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Wait');
  });

});

// Source: decompiled_lingo/11/11/casts/Internal/BehaviorScript 78 - MulleLogBH.ls
// Pattern: simple_transition
describe('BehaviorScript 78 - MulleLogBH.ls → Stopped', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'not__mode____TalkPek_', negated: true }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'whichFrame____Talk', negated: false }],
        actions: [{ type: 'go', target: 'Wait' }],
        children: [],
        elseBranch: null,
      }
    ],
      elseBranch: null,
    }
  ];

  test('branch 1: not (mode = #TalkPek), whichFrame = #Talk', () => {
    const ctx = createMockContext({ other: { not__mode____TalkPek_: false, whichFrame____Talk: true } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/BehaviorScript 78 - MulleLogBH.ls', 'Stopped', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Wait');
  });

});

// Source: decompiled_lingo/11/11/casts/Internal/MovieScript 2.ls
// Pattern: simple_transition
describe('MovieScript 2.ls → resultsFromScroller', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'type____EnteredSomething', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'type____ChoseLine', negated: false }],
          actions: [{ type: 'go', target: 'IntroStart' }],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [
            {
              conditions: [{ type: 'other', key: 'type____NewLine', negated: false }],
              actions: [{ type: 'go', target: 'IntroStart' }],
              children: [],
              elseBranch:               {
                conditions: [],
                actions: [],
                children: [
                {
                  conditions: [{ type: 'other', key: 'type____DeletedLine', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: null,
                }
              ],
                elseBranch: null,
              },
            }
          ],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: type = #EnteredSomething, type = #ChoseLine', () => {
    const ctx = createMockContext({ other: { type____ChoseLine: true, type____EnteredSomething: false } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/MovieScript 2.ls', 'resultsFromScroller', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('IntroStart');
  });

  test('branch 2: type = #EnteredSomething, type = #ChoseLine, type = #NewLine', () => {
    const ctx = createMockContext({ other: { type____ChoseLine: false, type____EnteredSomething: false, type____NewLine: true } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/MovieScript 2.ls', 'resultsFromScroller', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('IntroStart');
  });

});

// Source: decompiled_lingo/11/11/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: simple_transition
describe('ParentScript 1 - Dir.ls → resultsFromScroller', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'type____ChoseLine', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'login_the_users_of_gMulleGlobals__theStr', negated: false }],
        actions: [{ type: 'go', target: 'IntroStart' }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'type____NewLine', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'other', key: 'login_the_users_of_gMulleGlobals__theStr', negated: false }],
            actions: [{ type: 'go', target: 'IntroStart' }],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [
            {
              conditions: [{ type: 'other', key: 'type____DeletedLine', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            }
          ],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: type = #ChoseLine, login(the users of gMulleGlobals, theStr) = #Ok', () => {
    const ctx = createMockContext({ other: { login_the_users_of_gMulleGlobals__theStr: true, type____ChoseLine: true } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/ParentScript 1 - Dir.ls', 'resultsFromScroller', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('IntroStart');
  });

  test('branch 2: type = #ChoseLine, type = #NewLine, login(the users of gMulleGlobals, theStr) = #Ok', () => {
    const ctx = createMockContext({ other: { login_the_users_of_gMulleGlobals__theStr: true, type____ChoseLine: false, type____NewLine: true } });
    const contract = new LingoContract('decompiled_lingo/11/11/casts/Internal/ParentScript 1 - Dir.ls', 'resultsFromScroller', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('IntroStart');
  });

});
