/**
 * @fileoverview Behavioral parity tests for Lingo folder: 15
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 15.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/15/15/casts/Internal/BehaviorScript 2 - MainMenuBH.ls
// Pattern: simple_transition
describe('BehaviorScript 2 - MainMenuBH.ls → mouseUp', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'active', negated: false }],
      actions: [{ type: 'goVar', var: 'goToFrame' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: active', () => {
    const ctx = createMockContext({ other: { active: true } });
    const contract = new LingoContract('decompiled_lingo/15/15/casts/Internal/BehaviorScript 2 - MainMenuBH.ls', 'mouseUp', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:goToFrame');
  });

});

// Source: decompiled_lingo/15/15/casts/Internal/BehaviorScript 3 - GoMainMenuBH.ls
// Pattern: simple_transition
describe('BehaviorScript 3 - GoMainMenuBH.ls → mouseUp', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'MainMenu' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/15/15/casts/Internal/BehaviorScript 3 - GoMainMenuBH.ls', 'mouseUp', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('MainMenu');
  });

});

// Source: decompiled_lingo/15/15/casts/Internal/BehaviorScript 4 - ExitBluePrintBH.ls
// Pattern: simple_transition
describe('BehaviorScript 4 - ExitBluePrintBH.ls → mouseUp', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: '_tmpRudder_____NoRudder__and__tmpHull___', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'go', target: 'Shipyard' }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: (tmpRudder <> #NoRudder) and (tmpHull = #NoHull)', () => {
    const ctx = createMockContext({ other: { _tmpRudder_____NoRudder__and__tmpHull___: false } });
    const contract = new LingoContract('decompiled_lingo/15/15/casts/Internal/BehaviorScript 4 - ExitBluePrintBH.ls', 'mouseUp', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Shipyard');
  });

});

// Source: decompiled_lingo/15/15/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: inventory_check
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'tmpHull_____NoType', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'the_gotNewHull_of_gMulleGlobals', negated: false }],
        actions: [],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'inventory', key: 'Blueprint1', negated: true }],
          actions: [{ type: 'go', target: 'Small' }],
          children: [],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: tmpHull <> #NoType, without Blueprint1', () => {
    const ctx = createMockContext({ inventory: { Blueprint1: false }, other: { tmpHull_____NoType: false } });
    const contract = new LingoContract('decompiled_lingo/15/15/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Small');
  });

});
