/**
 * @fileoverview Behavioral parity tests for Lingo folder: 76
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 76.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/76/76/casts/Internal/BehaviorScript 2.ls
// Pattern: simple_transition
describe('BehaviorScript 2.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/76/76/casts/Internal/BehaviorScript 2.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/76/76/casts/Internal/BehaviorScript 6.ls
// Pattern: simple_transition
describe('BehaviorScript 6.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/76/76/casts/Internal/BehaviorScript 6.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/76/76/casts/Internal/BehaviorScript 7.ls
// Pattern: simple_transition
describe('BehaviorScript 7.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/76/76/casts/Internal/BehaviorScript 7.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/76/76/casts/Internal/ParentScript 4 - Dir.ls
// Pattern: simple_transition
describe('ParentScript 4 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'tmpFun___4', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'tmpFun___10', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'tmpFun___20', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'other', key: 'tmpFun___25', negated: false }],
            actions: [{ type: 'addMedal', medal: 4 }],
            children: [],
            elseBranch: null,
          }
        ],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: tmpFun > 4, tmpFun > 10, tmpFun > 20, tmpFun > 25', () => {
    const ctx = createMockContext({ other: { tmpFun___10: true, tmpFun___20: true, tmpFun___25: true, tmpFun___4: true } });
    const contract = new LingoContract('decompiled_lingo/76/76/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.medalsAdded).toContain(4);
  });

});
