/**
 * @fileoverview Behavioral parity tests for Lingo folder: 78
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 78.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/78/78/casts/Internal/BehaviorScript 2.ls
// Pattern: simple_transition
describe('BehaviorScript 2.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/78/78/casts/Internal/BehaviorScript 2.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/78/78/casts/Internal/BehaviorScript 3.ls
// Pattern: simple_transition
describe('BehaviorScript 3.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'BibleLeave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/78/78/casts/Internal/BehaviorScript 3.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('BibleLeave');
  });

});

// Source: decompiled_lingo/78/78/casts/Internal/ParentScript 4 - Dir.ls
// Pattern: complex_branching
describe('ParentScript 4 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'objId', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'missionGiven', key: '1', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'inventory', key: 'tmpStuffNeeded', negated: false }],
        actions: [{ type: 'deleteFromInventory', item: 'tmpStuffNeeded' }, { type: 'addCompletedMission', mission: 1 }],
        children: [
        {
          conditions: [{ type: 'other', key: 'getCompletedMissionInfo_the_user_of_gMul', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'other', key: 'getCompletedMissionInfo_the_user_of_gMul', negated: false }],
            actions: [],
            children: [],
            elseBranch: null,
          },
          {
            conditions: [{ type: 'other', key: 'givePart____NoPart', negated: false }],
            actions: [{ type: 'setInInventory', item: 'Belly' }],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [{ type: 'addNewPart' }],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [{ type: 'setInInventory', item: 'Belly' }],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionCompleted', key: '20', negated: true }],
      actions: [{ type: 'addCompletedMission', mission: 20 }],
      children: [
      {
        conditions: [{ type: 'missionGiven', key: '1', negated: true }],
        actions: [{ type: 'addGivenMission', mission: 1 }],
        children: [],
        elseBranch: null,
      }
    ],
      elseBranch: null,
    }
  ];

  test('branch 1: mission 1 given, with tmpStuffNeeded, getCompletedMissionInfo(the user of gMulleGlobals,, givePart = #NoPart', () => {
    const ctx = createMockContext({ inventory: { tmpStuffNeeded: true }, missionsGiven: { '1': true }, other: { getCompletedMissionInfo_the_user_of_gMul: true, givePart____NoPart: true } });
    const contract = new LingoContract('decompiled_lingo/78/78/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('Belly');
  });

  test('branch 2: mission 1 given, with tmpStuffNeeded, getCompletedMissionInfo(the user of gMulleGlobals,, givePart = #NoPart', () => {
    const ctx = createMockContext({ inventory: { tmpStuffNeeded: true }, missionsGiven: { '1': true }, other: { getCompletedMissionInfo_the_user_of_gMul: true, givePart____NoPart: false } });
    const contract = new LingoContract('decompiled_lingo/78/78/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.partsAdded).toBeGreaterThan(0);
  });

  test('branch 3: mission 1 given, with tmpStuffNeeded, getCompletedMissionInfo(the user of gMulleGlobals,', () => {
    const ctx = createMockContext({ inventory: { tmpStuffNeeded: true }, missionsGiven: { '1': true }, other: { getCompletedMissionInfo_the_user_of_gMul: false } });
    const contract = new LingoContract('decompiled_lingo/78/78/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('Belly');
  });

  test('branch 4: mission 20 not completed, mission 1 not given', () => {
    const ctx = createMockContext({ missionsCompleted: { '20': false }, missionsGiven: { '1': false } });
    const contract = new LingoContract('decompiled_lingo/78/78/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsGiven).toContain(1);
  });

});
