/**
 * @fileoverview Behavioral parity tests for Lingo folder: 83
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 83.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 23.ls
// Pattern: simple_transition
describe('BehaviorScript 23.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'infiniteJustDoIt2' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 23.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('infiniteJustDoIt2');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 24.ls
// Pattern: simple_transition
describe('BehaviorScript 24.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'boatride2' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 24.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('boatride2');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 3.ls
// Pattern: simple_transition
describe('BehaviorScript 3.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 3.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 31.ls
// Pattern: simple_transition
describe('BehaviorScript 31.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'boatride3' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 31.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('boatride3');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 32.ls
// Pattern: simple_transition
describe('BehaviorScript 32.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'justDoITluck2' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 32.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('justDoITluck2');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 5.ls
// Pattern: simple_transition
describe('BehaviorScript 5.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'story1' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 5.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('story1');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 7.ls
// Pattern: simple_transition
describe('BehaviorScript 7.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'boatride' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 7.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('boatride');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/BehaviorScript 9.ls
// Pattern: simple_transition
describe('BehaviorScript 9.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'justdoit2' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/BehaviorScript 9.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('justdoit2');
  });

});

// Source: decompiled_lingo/83/83/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: mission_check
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'objId', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'missionCompleted', key: '25', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'missionGiven', key: '13', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'property', key: 'Bench', negated: false }],
            actions: [],
            children: [
            {
              conditions: [{ type: 'missionCompleted', key: '13', negated: false }],
              actions: [{ type: 'addCompletedMission', mission: 13 }],
              children: [],
              elseBranch:               {
                conditions: [],
                actions: [{ type: 'addCompletedMission', mission: 13 }, { type: 'addNewPart' }],
                children: [],
                elseBranch: null,
              },
            }
          ],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'missionCompleted', key: '25', negated: true }],
        actions: [{ type: 'addCompletedMission', mission: 25 }],
        children: [],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: 'myMarker____nomission_', negated: false }],
        actions: [{ type: 'addGivenMission', mission: 13 }, { type: 'addNewPart' }, { type: 'go', target: 'start' }],
        children: [
        {
          conditions: [{ type: 'property', key: 'Bench', negated: false }],
          actions: [{ type: 'addCompletedMission', mission: 13 }],
          children: [],
          elseBranch: null,
        }
      ],
        elseBranch:         {
          conditions: [],
          actions: [{ type: 'goVar', var: 'myMarker' }],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch: null,
    }
  ];

  test('branch 1: objId, mission 25 completed, mission 13 given, with boat.Bench, mission 13 completed', () => {
    const ctx = createMockContext({ boatProperties: { Bench: true }, missionsCompleted: { '13': true, '25': true }, missionsGiven: { '13': true }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(13);
  });

  test('branch 2: objId, mission 25 completed, mission 13 given, with boat.Bench, mission 13 not completed', () => {
    const ctx = createMockContext({ boatProperties: { Bench: true }, missionsCompleted: { '13': false, '25': true }, missionsGiven: { '13': true }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(13);
    expect(result.partsAdded).toBeGreaterThan(0);
  });

  test('branch 3: objId, mission 25 not completed', () => {
    const ctx = createMockContext({ missionsCompleted: { '25': false }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(25);
  });

  test('branch 4: objId, myMarker = "nomission", with boat.Bench', () => {
    const ctx = createMockContext({ boatProperties: { Bench: true }, other: { myMarker____nomission_: true, objId: true } });
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(13);
  });

  test('branch 5: objId, myMarker = "nomission"', () => {
    const ctx = createMockContext({ other: { myMarker____nomission_: false, objId: true } });
    const contract = new LingoContract('decompiled_lingo/83/83/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:myMarker');
  });

});
