/**
 * @fileoverview Behavioral parity tests for Lingo folder: 85
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 85.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/85/85/casts/Internal/BehaviorScript 6.ls
// Pattern: simple_transition
describe('BehaviorScript 6.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/BehaviorScript 6.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/85/85/casts/Internal/BehaviorScript 7.ls
// Pattern: simple_transition
describe('BehaviorScript 7.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/BehaviorScript 7.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/85/85/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: complex_branching
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionCompleted', key: '7', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'missionGiven', key: '8', negated: false }],
        actions: [{ type: 'setInInventory', item: 'Suit' }, { type: 'addCompletedMission', mission: 8 }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'missionGiven', key: '7', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'inventory', key: 'Diary', negated: true }],
            actions: [{ type: 'setInInventory', item: 'Diary' }],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'myMarker___VOID', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: 'myMarker____Diary_', negated: false }],
      actions: [{ type: 'go', target: 'StartDiary' }],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: 'myMarker____Leave_', negated: false }],
      actions: [{ type: 'go', target: 'Start' }],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: 'myMarker____suit_', negated: false }],
      actions: [{ type: 'go', target: 'suit' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: mission 7 completed, mission 8 given', () => {
    const ctx = createMockContext({ missionsCompleted: { '7': true }, missionsGiven: { '8': true } });
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('Suit');
    expect(result.missionsCompleted).toContain(8);
  });

  test('branch 2: mission 7 not completed, mission 7 given, without Diary', () => {
    const ctx = createMockContext({ inventory: { Diary: false }, missionsCompleted: { '7': false }, missionsGiven: { '7': true } });
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('Diary');
  });

  test('branch 3: myMarker = "Diary"', () => {
    const ctx = createMockContext({ other: { myMarker____Diary_: true } });
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('StartDiary');
  });

  test('branch 4: myMarker = "Leave"', () => {
    const ctx = createMockContext({ other: { myMarker____Leave_: true } });
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Start');
  });

  test('branch 5: myMarker = "suit"', () => {
    const ctx = createMockContext({ other: { myMarker____suit_: true } });
    const contract = new LingoContract('decompiled_lingo/85/85/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('suit');
  });

});
