/**
 * @fileoverview Behavioral parity tests for Lingo folder: 88
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 88.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/88/88/casts/Internal/BehaviorScript 6.ls
// Pattern: simple_transition
describe('BehaviorScript 6.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/88/88/casts/Internal/BehaviorScript 6.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/88/88/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: mission_check
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionCompleted', key: '24', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'missionCompleted', key: '11', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'property', key: 'Watertank', negated: false }],
            actions: [{ type: 'addCompletedMission', mission: 24 }, { type: 'setInInventory', item: 'Fishingrod' }],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'myMarker_____cantDoiT_', negated: false }],
      actions: [{ type: 'goVar', var: 'myMarker' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'go', target: 'start' }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: mission 24 not completed, mission 11 completed, with boat.Watertank', () => {
    const ctx = createMockContext({ boatProperties: { Watertank: true }, missionsCompleted: { '11': true, '24': false } });
    const contract = new LingoContract('decompiled_lingo/88/88/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(24);
    expect(result.inventorySet).toContain('Fishingrod');
  });

  test('branch 2: myMarker <> "cantDoiT"', () => {
    const ctx = createMockContext({ other: { myMarker_____cantDoiT_: true } });
    const contract = new LingoContract('decompiled_lingo/88/88/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:myMarker');
  });

  test('branch 3: myMarker <> "cantDoiT"', () => {
    const ctx = createMockContext({ other: { myMarker_____cantDoiT_: false } });
    const contract = new LingoContract('decompiled_lingo/88/88/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('start');
  });

});
