/**
 * @fileoverview Behavioral parity tests for Lingo folder: 03
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 03 (garage, boat_yard).
 */

const { LingoContract, createMockContext } = require('./helpers');

describe('03 Lingo behavioral parity', () => {
  describe('BehaviorScript 10 - GiftWait', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'the_ticks_lt_endTime', negated: false }],
          actions: [{ type: 'goFrame' }],
          children: [],
          elseBranch: {
            conditions: [],
            actions: [{ type: 'go', target: '03' }],
            children: [],
            elseBranch: null,
          },
        },
      ];

      test('path 1: (the ticks < endTime) → go(the frame)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 10 - GiftWait', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });

      test('path 2: NOT (the ticks < endTime) → go(1, "03")', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 10 - GiftWait', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('03');
      });

    });

  });

  describe('BehaviorScript 19 - MulleYardBH', () => {
    describe('Stopped', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'mode_eq_Talk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'currentAnimChart_eq_TalkToMe', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the mode of nil = #Talk), (currentAnimChart = #TalkToMe)', () => {
        const ctx = createMockContext({ other: { mode_eq_Talk: true, currentAnimChart_eq_TalkToMe: true } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        // Animation state-machine path — no modeled transition
        expect(result.transition).toBeNull();
      });

      test('path 2: (the mode of nil = #Talk), NOT (currentAnimChart = #TalkToMe)', () => {
        const ctx = createMockContext({ other: { mode_eq_Talk: true, currentAnimChart_eq_TalkToMe: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: the mode of nil = otherwise', () => {
        const ctx = createMockContext({ other: { mode_eq_Talk: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'Stopped', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('makeMulleTalk', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'argAction_eq_NormalTalk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'random_2_eq_1', negated: false }],
                  actions: [],
                  children: [],
                  elseBranch: null,
                },
              ],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'argAction_eq_InfoTalk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
        {
          conditions: [{ type: 'other', key: 'argAction_eq_PrioTalk', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'mode_eq_Wait_or_Talk', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (the argAction of nil = #NormalTalk), (mode = #Wait), (random(2) = 1)', () => {
        const ctx = createMockContext({ other: { argAction_eq_NormalTalk: true, mode_eq_Wait: true, random_2_eq_1: true } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: (the argAction of nil = #NormalTalk), (mode = #Wait), NOT (random(2) = 1)', () => {
        const ctx = createMockContext({ other: { argAction_eq_NormalTalk: true, mode_eq_Wait: true, random_2_eq_1: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: (the argAction of nil = #NormalTalk), NOT (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { argAction_eq_NormalTalk: true, mode_eq_Wait: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: (the argAction of nil = #InfoTalk), (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { argAction_eq_InfoTalk: true, mode_eq_Wait: true } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: (the argAction of nil = #InfoTalk), NOT (mode = #Wait)', () => {
        const ctx = createMockContext({ other: { argAction_eq_InfoTalk: true, mode_eq_Wait: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: (the argAction of nil = #PrioTalk), ((mode = #Wait) OR (mode = #Talk))', () => {
        const ctx = createMockContext({ other: { argAction_eq_PrioTalk: true, mode_eq_Wait_or_Talk: true } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: (the argAction of nil = #PrioTalk), ((mode = #Wait) OR (mode = #Talk))', () => {
        const ctx = createMockContext({ other: { argAction_eq_PrioTalk: true, mode_eq_Wait_or_Talk: false } });
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 19 - MulleYardBH', 'makeMulleTalk', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

  describe('BehaviorScript 3 - GoQuay', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '04' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "04")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 3 - GoQuay', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('04');
      });

    });

  });

  describe('BehaviorScript 4 - GoShelf1', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '02' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "02")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 4 - GoShelf1', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('02');
      });

    });

  });

  describe('BehaviorScript 5 - GoShelf2', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '02' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "02")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 5 - GoShelf2', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('02');
      });

    });

  });

  describe('BehaviorScript 6 - GoShelf3', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '02' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "02")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 6 - GoShelf3', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('02');
      });

    });

  });

  describe('BehaviorScript 7 - GoShelf4', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '02' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "02")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 7 - GoShelf4', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('02');
      });

    });

  });

  describe('BehaviorScript 8 - GoShelf5', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '02' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "02")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 8 - GoShelf5', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('02');
      });

    });

  });

  describe('BehaviorScript 9 - GoShelf6', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '02' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "02")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/03/BehaviorScript 9 - GoShelf6', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('02');
      });

    });

  });

  describe('ParentScript 2 - Dir', () => {
    describe('init', () => {
      // Both paths call setSky — a runtime side-effect not modeled by LingoContract.
      // The condition (gotGifts) controls gift-related setup but both paths
      // converge on the same setSky call.
      const branches = [
        {
          conditions: [{ type: 'other', key: 'gotGifts', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: gotGifts → setSky(the weather of gMulleGlobals)', () => {
        const ctx = createMockContext({ other: { gotGifts: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        // setSky is a rendering call; contract verifies the path is reachable
        expect(result.transition).toBeNull();
      });

      test('path 2: NOT gotGifts → setSky(the weather of gMulleGlobals)', () => {
        const ctx = createMockContext({ other: { gotGifts: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'init', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('kill', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'objectp_giftMouseObject', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: objectp(giftMouseObject)', () => {
        const ctx = createMockContext({ other: { objectp_giftMouseObject: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'kill', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: NOT objectp(giftMouseObject)', () => {
        const ctx = createMockContext({ other: { objectp_giftMouseObject: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'kill', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('loop', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'OKToTalk_AND_dialogClosed', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'loopCounter_gt_0', negated: false }],
              actions: [],
              children: [
                {
                  conditions: [{ type: 'other', key: 'gotNewParts', negated: false }],
                  actions: [],
                  children: [
                    {
                      conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
                      actions: [],
                      children: [],
                      elseBranch: null,
                    },
                  ],
                  elseBranch: {
                    conditions: [],
                    actions: [],
                    children: [
                      {
                        conditions: [{ type: 'other', key: 'gotGifts', negated: false }],
                        actions: [],
                        children: [
                          {
                            conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
                            actions: [],
                            children: [],
                            elseBranch: null,
                          },
                        ],
                        elseBranch: {
                          conditions: [],
                          actions: [],
                          children: [
                            {
                              conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
                              actions: [],
                              children: [],
                              elseBranch: null,
                            },
                          ],
                          elseBranch: null,
                        },
                      },
                    ],
                    elseBranch: null,
                  },
                },
              ],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: OKToTalk AND dialogClosed, (loopCounter > 0), the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: OKToTalk AND dialogClosed, (loopCounter > 0), the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: true, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 4: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: true, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 5: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: false, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 6: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: false, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 7: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: false, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 8: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: false, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 9: OKToTalk AND dialogClosed, (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: true, gotNewParts: false, gotGifts: false, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 10: OKToTalk AND dialogClosed, NOT (loopCounter > 0), the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 11: OKToTalk AND dialogClosed, NOT (loopCounter > 0), the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: true, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 12: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 13: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: true, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 14: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: false, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 15: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: false, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 16: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: false, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 17: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: false, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 18: OKToTalk AND dialogClosed, NOT (loopCounter > 0), NOT the gotNewParts of gMulleGlobals', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: true, loopCounter_gt_0: false, gotNewParts: false, gotGifts: false, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 19: OKToTalk AND dialogClosed', () => {
        const ctx = createMockContext({ other: { OKToTalk_AND_dialogClosed: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'loop', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('mouse', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'argWhat_eq_click', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'dragToWhere_eq_Gift', negated: false }],
              actions: [{ type: 'go', target: 'Gift' }],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: (argWhat = #click), (the dragToWhere of the argObj of nil = #Gift) → go("Gift")', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, dragToWhere_eq_Gift: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('Gift');
      });

      test('path 2: (argWhat = #click)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: true, dragToWhere_eq_Gift: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: NOT (argWhat = #click)', () => {
        const ctx = createMockContext({ other: { argWhat_eq_click: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'mouse', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('new', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'not_voidp_FirstTime', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: NOT voidp(FirstTime), FirstTime', () => {
        const ctx = createMockContext({ other: { not_voidp_FirstTime: true, FirstTime: true } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 2: NOT voidp(FirstTime), NOT FirstTime', () => {
        const ctx = createMockContext({ other: { not_voidp_FirstTime: true, FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

      test('path 3: voidp(FirstTime)', () => {
        const ctx = createMockContext({ other: { not_voidp_FirstTime: false } });
        const contract = new LingoContract('decompiled_lingo/03/ParentScript 2 - Dir', 'new', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

});
