/**
 * @fileoverview Behavioral parity tests for Lingo folder: 04
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 04.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls
// Pattern: mission_check
describe('ParentScript 22 - Dir.ls → new', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'not_voidp_FirstTime_', negated: true }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'FirstTime', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'isItTheVeryFirstTime_the_user_of_gMulleG', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionCompleted', key: '20', negated: false }],
      actions: [{ type: 'addGivenMission', mission: 1 }],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'missionCompleted', key: '2', negated: false }],
      actions: [{ type: 'addGivenMission', mission: 2 }],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'missionCompleted', key: '13', negated: false }],
      actions: [{ type: 'addGivenMission', mission: 13 }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: mission 20 completed', () => {
    const ctx = createMockContext({ missionsCompleted: { '20': true } });
    const contract = new LingoContract('decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls', 'new', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsGiven).toContain(1);
  });

  test('branch 2: mission 2 completed', () => {
    const ctx = createMockContext({ missionsCompleted: { '2': true } });
    const contract = new LingoContract('decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls', 'new', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsGiven).toContain(2);
  });

  test('branch 3: mission 13 completed', () => {
    const ctx = createMockContext({ missionsCompleted: { '13': true } });
    const contract = new LingoContract('decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls', 'new', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsGiven).toContain(13);
  });

});

// Source: decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls
// Pattern: simple_transition
describe('ParentScript 22 - Dir.ls → mouse', () => {
  const branches = [
    {
      conditions: [{ type: 'property', key: 'engine', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'property', key: 'Material', negated: false }],
        actions: [{ type: 'go', target: 'WoodWorld' }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [{ type: 'go', target: 'MetalWorld' }],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with boat.engine, with boat.Material', () => {
    const ctx = createMockContext({ boatProperties: { Material: true, engine: true } });
    const contract = new LingoContract('decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls', 'mouse', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('WoodWorld');
  });

  test('branch 2: with boat.engine, without boat.Material', () => {
    const ctx = createMockContext({ boatProperties: { Material: false, engine: true } });
    const contract = new LingoContract('decompiled_lingo/04/04/casts/Internal/ParentScript 22 - Dir.ls', 'mouse', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('MetalWorld');
  });

});
