/**
 * @fileoverview Behavioral parity tests for Lingo folder: 05
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 05.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/05/05/casts/Internal/ParentScript 2 - Dir.ls
// Pattern: simple_transition
describe('ParentScript 2 - Dir.ls → prepareToLeave', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'isLeaving', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: '_argToDir____04___or__argToDir____03__', negated: false }],
      actions: [{ type: 'go', target: 'Leave' }],
      children: [
      {
        conditions: [{ type: 'other', key: 'voidp_transPic_', negated: false }],
        actions: [],
        children: [],
        elseBranch: null,
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'argToDir____08_', negated: false }],
          actions: [{ type: 'go', target: 'Leave' }],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [{ type: 'go', target: 'Leave' }],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: (argToDir = "04") or (argToDir = "03"), argToDir = "08"', () => {
    const ctx = createMockContext({ other: { _argToDir____04___or__argToDir____03__: false, argToDir____08_: true } });
    const contract = new LingoContract('decompiled_lingo/05/05/casts/Internal/ParentScript 2 - Dir.ls', 'prepareToLeave', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Leave');
  });

  test('branch 2: (argToDir = "04") or (argToDir = "03"), argToDir = "08"', () => {
    const ctx = createMockContext({ other: { _argToDir____04___or__argToDir____03__: false, argToDir____08_: false } });
    const contract = new LingoContract('decompiled_lingo/05/05/casts/Internal/ParentScript 2 - Dir.ls', 'prepareToLeave', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Leave');
  });

});

// Source: decompiled_lingo/05/05/casts/Internal/ParentScript 34 - BoatBase.ls
// Pattern: complex_branching
describe('ParentScript 34 - BoatBase.ls → loop', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'programControlsBoat', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: '_tmpInfo____Hit__or__tmpInfo___1_', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'not_changedMapRecently', negated: true }],
        actions: [],
        children: [],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: 'finished_gSound__crashSndID_', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'getaProp_quickProps___weight____100', negated: false }],
          actions: [],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        },
        {
          conditions: [{ type: 'other', key: 'tmpReceivedDamage___300', negated: false }],
          actions: [],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [
            {
              conditions: [{ type: 'other', key: 'tmpReceivedDamage___100', negated: false }],
              actions: [],
              children: [],
              elseBranch:               {
                conditions: [],
                actions: [],
                children: [],
                elseBranch: null,
              },
            }
          ],
            elseBranch: null,
          },
        },
        {
          conditions: [{ type: 'other', key: 'crashSndID', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: 'not_inFreeZone', negated: true }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'Durability____0', negated: true }],
          actions: [],
          children: [],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: '_loc____getAt_locHistory__count_locHisto', negated: false }],
        actions: [],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'tmpInfo____Shallow', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'other', key: 'shallowCommentCounter___500', negated: false }],
            actions: [],
            children: [],
            elseBranch: null,
          },
          {
            conditions: [{ type: 'other', key: '__shallowCommentCounter_mod_50____0__or_', negated: true }],
            actions: [],
            children: [],
            elseBranch: null,
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'not_inFreeZone', negated: true }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'level____4', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'buffaSick___0', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'other', key: 'buffaSick____0', negated: true }],
            actions: [],
            children: [
            {
              conditions: [{ type: 'missionCompleted', key: '3', negated: false }],
              actions: [{ type: 'addGivenMission', mission: 3 }],
              children: [],
              elseBranch: null,
            }
          ],
            elseBranch: null,
          }
        ],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: 'mulleHunger___0', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'mulleHunger____0', negated: true }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'inventory', key: 'Fishingrod', negated: false }],
            actions: [],
            children: [
            {
              conditions: [{ type: 'inventory', key: 'Fished', negated: false }],
              actions: [],
              children: [],
              elseBranch:               {
                conditions: [],
                actions: [{ type: 'setInInventory', item: 'Fished' }],
                children: [],
                elseBranch: null,
              },
            }
          ],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      }
    ],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: 'argAdditionalSideForce', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'abs_tmpSideAngle____30', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'not_inFreeZone', negated: true }],
        actions: [],
        children: [],
        elseBranch: null,
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'abs_tmpSideAngle____27', negated: false }],
          actions: [],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [
            {
              conditions: [{ type: 'other', key: 'abs_tmpSideAngle____23', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            }
          ],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'abs_side____2', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: 'abs_frontBack____2', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: not inFreeZone, level >= 4, buffaSick > 0, buffaSick <= 0, mission 3 completed', () => {
    const ctx = createMockContext({ missionsCompleted: { '3': true }, other: { buffaSick___0: true, buffaSick____0: false, level____4: true, not_inFreeZone: false } });
    const contract = new LingoContract('decompiled_lingo/05/05/casts/Internal/ParentScript 34 - BoatBase.ls', 'loop', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsGiven).toContain(3);
  });

  test('branch 2: not inFreeZone, mulleHunger > 0, mulleHunger <= 0, with Fishingrod, without Fished', () => {
    const ctx = createMockContext({ inventory: { Fished: false, Fishingrod: true }, other: { mulleHunger___0: true, mulleHunger____0: false, not_inFreeZone: false } });
    const contract = new LingoContract('decompiled_lingo/05/05/casts/Internal/ParentScript 34 - BoatBase.ls', 'loop', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('Fished');
  });

});
