/**
 * @fileoverview Behavioral parity tests for Lingo folder: 06
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 06.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/06/06/casts/Internal/BehaviorScript 1.ls
// Pattern: simple_transition
describe('BehaviorScript 1.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'symbolp_the_doNextFrame_of_gDir_', negated: false }],
      actions: [{ type: 'go', target: 'Leave' }, { type: 'goFrame' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: symbolp(the doNextFrame of gDir)', () => {
    const ctx = createMockContext({ other: { symbolp_the_doNextFrame_of_gDir_: true } });
    const contract = new LingoContract('decompiled_lingo/06/06/casts/Internal/BehaviorScript 1.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    // Case #jump → go("Leave"), case #activateScreen → go(the frame)
    // The transition depends on the case value; either is valid
    expect(['Leave', 'frame']).toContain(result.transition);
  });

});
