/**
 * @fileoverview Behavioral parity tests for Lingo folder: 08
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 08.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/08/08/casts/Internal/BehaviorScript 34 - GoBackBH.ls
// Pattern: simple_transition
describe('BehaviorScript 34 - GoBackBH.ls → mouseUp', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'Leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/08/08/casts/Internal/BehaviorScript 34 - GoBackBH.ls', 'mouseUp', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('Leave');
  });

});

// Source: decompiled_lingo/08/08/casts/Internal/BehaviorScript 4.ls
// Pattern: simple_transition
describe('BehaviorScript 4.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'goVar', var: '1' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/08/08/casts/Internal/BehaviorScript 4.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:1');
  });

});
