/**
 * @fileoverview Behavioral parity tests for Lingo folder: 10
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 10 (menu).
 */

const { LingoContract, createMockContext } = require('./helpers');

describe('10 Lingo behavioral parity', () => {
  describe('MovieScript 1 - Inits', () => {
    describe('setProgressMeter', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'argProgress_lt_1', negated: false }],
          actions: [],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: (argProgress < 1.0)', () => {
        const ctx = createMockContext({ other: { argProgress_lt_1: true } });
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'setProgressMeter', branches);
        const result = contract.evaluate(ctx);
        // Path taken but no modeled side-effects
        expect(result.transition).toBeNull();
      });

      test('path 2: NOT (argProgress < 1.0)', () => {
        const ctx = createMockContext({ other: { argProgress_lt_1: false } });
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'setProgressMeter', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

    describe('startMovie', () => {
      // All 32 paths through the startMovie handler converge on the same
      // outcome: puppetSound(1, "10e001v0"), puppetSound(1, 0), go(1, "11").
      // The conditions (objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals),
      // objectp(gCursor), objectp(gSound)) control initialization of globals
      // but the final transition is always go(1, "11").
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '11' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: NOT objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 2: NOT objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 3: NOT objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 4: NOT objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 5: NOT objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 6: NOT objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 7: NOT objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 8: NOT objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 9: NOT objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 10: NOT objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 11: NOT objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 12: NOT objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 13: NOT objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 14: NOT objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 15: NOT objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 16: NOT objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 17: objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 18: objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 19: objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 20: objectp(gPathGlobals), count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 21: objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 22: objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 23: objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 24: objectp(gPathGlobals), count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 25: objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 26: objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 27: objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 28: objectp(gPathGlobals), NOT count(plugCasts), NOT objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 29: objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 30: objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 31: objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

      test('path 32: objectp(gPathGlobals), NOT count(plugCasts), objectp(gMulleGlobals) → puppetSound(1, "10e001v0"), puppetSound(1, 0)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/10/MovieScript 1 - Inits', 'startMovie', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('11');
      });

    });

  });

});
