/**
 * @fileoverview Behavioral parity tests for Lingo folder: 12
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 12 (credits).
 */

const { LingoContract, createMockContext } = require('./helpers');

describe('12 Lingo behavioral parity', () => {
  // BehaviorScripts 1, 10–12, 14–21, 23–29: all unconditional go(the frame)
  const goFrameBranches = [
    {
      conditions: [],
      actions: [{ type: 'goFrame' }],
      children: [],
      elseBranch: null,
    },
  ];

  describe('BehaviorScript 1', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 1', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 10', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 10', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 11', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 11', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 12', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 12', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 14', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 14', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 15', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 15', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 16', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 16', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 17', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 17', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 18', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 18', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 19', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 19', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 20', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 20', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 21', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 21', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 23', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 23', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 24', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 24', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 25', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 25', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 26', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 26', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 27', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 27', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 28', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 28', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 29', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 29', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('BehaviorScript 3', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '1' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "01.dir")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 3', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('1');
      });
    });
  });

  describe('BehaviorScript 7', () => {
    describe('exitFrame', () => {
      test('path 1: unconditional → go(the frame)', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/BehaviorScript 7', 'exitFrame', goFrameBranches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });
    });
  });

  describe('MovieScript 4 - cuecommands', () => {
    describe('CuePassed', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'goVar', var: 'marker_1' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(marker(1))', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/MovieScript 4 - cuecommands', 'CuePassed', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('var:marker_1');
      });
    });

    describe('keyDown', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'the_key_eq_RETURN', negated: false }],
          actions: [{ type: 'go', target: '1' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: (the key = RETURN) → go(1, "01.dir")', () => {
        const ctx = createMockContext({ other: { the_key_eq_RETURN: true } });
        const contract = new LingoContract('decompiled_lingo/12/MovieScript 4 - cuecommands', 'keyDown', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('1');
      });

      test('path 2: NOT (the key = RETURN)', () => {
        const ctx = createMockContext({ other: { the_key_eq_RETURN: false } });
        const contract = new LingoContract('decompiled_lingo/12/MovieScript 4 - cuecommands', 'keyDown', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });
    });

    describe('mouseUp', () => {
      const branches = [
        {
          conditions: [],
          actions: [{ type: 'go', target: '1' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → go(1, "01.dir")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/12/MovieScript 4 - cuecommands', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('1');
      });
    });

  });

});
