/**
 * @fileoverview Behavioral parity tests for Lingo folder: 13
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 13 (dlcshop).
 */

const { LingoContract, createMockContext } = require('./helpers');

describe('13 Lingo behavioral parity', () => {
  describe('BehaviorScript 10', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'the_ticks_lt_endTime', negated: false }],
          actions: [{ type: 'goFrame' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: (the ticks < endTime) → go(the frame)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: true } });
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 10', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });

      test('path 2: NOT (the ticks < endTime)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: false } });
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 10', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

  describe('BehaviorScript 31', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'the_ticks_lt_endTime', negated: false }],
          actions: [{ type: 'goFrame' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: (the ticks < endTime) → go(the frame)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: true } });
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 31', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });

      test('path 2: NOT (the ticks < endTime)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: false } });
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 31', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

  describe('BehaviorScript 32', () => {
    describe('exitFrame', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'the_ticks_lt_endTime', negated: false }],
          actions: [{ type: 'goFrame' }],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: (the ticks < endTime) → go(the frame)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: true } });
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 32', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame');
      });

      test('path 2: NOT (the ticks < endTime)', () => {
        const ctx = createMockContext({ other: { the_ticks_lt_endTime: false } });
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 32', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

  describe('BehaviorScript 4', () => {
    describe('exitFrame', () => {
      // puppetSound is a runtime side-effect not modeled by LingoContract;
      // verify the unconditional path is always taken.
      const branches = [
        {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      ];

      test('path 1: unconditional → puppetSound(2, "04e004v0")', () => {
        const ctx = createMockContext();
        const contract = new LingoContract('decompiled_lingo/13/BehaviorScript 4', 'exitFrame', branches);
        const result = contract.evaluate(ctx);
        // puppetSound is an audio side-effect; the contract has no branching
        expect(result.transition).toBeNull();
        expect(result.inventoryDeleted).toEqual([]);
      });

    });

  });

  describe('MovieScript 1', () => {
    describe('mouseUp', () => {
      const branches = [
        {
          conditions: [{ type: 'other', key: 'voidp_gAlreadyDone', negated: false }],
          actions: [],
          children: [
            {
              conditions: [{ type: 'other', key: 'the_doubleClick', negated: false }],
              actions: [{ type: 'go', target: 'Eldmatch' }],
              children: [],
              elseBranch: {
                conditions: [],
                actions: [{ type: 'goFramePlus', offset: 1 }],
                children: [],
                elseBranch: null,
              },
            },
          ],
          elseBranch: null,
        },
      ];

      test('path 1: voidp(gAlreadyDone), the doubleClick → go("Eldmatch")', () => {
        const ctx = createMockContext({ other: { voidp_gAlreadyDone: true, the_doubleClick: true } });
        const contract = new LingoContract('decompiled_lingo/13/MovieScript 1', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('Eldmatch');
      });

      test('path 2: voidp(gAlreadyDone), NOT the doubleClick → go((the frame + 1))', () => {
        const ctx = createMockContext({ other: { voidp_gAlreadyDone: true, the_doubleClick: false } });
        const contract = new LingoContract('decompiled_lingo/13/MovieScript 1', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBe('frame+1');
      });

      test('path 3: NOT voidp(gAlreadyDone)', () => {
        const ctx = createMockContext({ other: { voidp_gAlreadyDone: false } });
        const contract = new LingoContract('decompiled_lingo/13/MovieScript 1', 'mouseUp', branches);
        const result = contract.evaluate(ctx);
        expect(result.transition).toBeNull();
      });

    });

  });

});
