/**
 * @fileoverview Behavioral parity tests for Lingo folder: 70
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 70.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/70/70/casts/Internal/BehaviorScript 2.ls
// Pattern: simple_transition
describe('BehaviorScript 2.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/70/70/casts/Internal/BehaviorScript 2.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/70/70/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: inventory_check
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'objId', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'inventory', key: 'helmet', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'inventory', key: 'Suit', negated: false }],
          actions: [{ type: 'addCompletedMission', mission: 15 }],
          children: [
          {
            conditions: [{ type: 'other', key: 'givePart____NoPart', negated: false }],
            actions: [],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [{ type: 'addNewPart' }],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch: null,
    }
  ];

  test('branch 1: objId, with helmet, with Suit, givePart = #NoPart', () => {
    const ctx = createMockContext({ inventory: { Suit: true, helmet: true }, other: { givePart____NoPart: false, objId: true } });
    const contract = new LingoContract('decompiled_lingo/70/70/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.partsAdded).toBeGreaterThan(0);
  });

});
