/**
 * @fileoverview Behavioral parity tests for Lingo folder: 71
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 71.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/71/71/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: simple_transition
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'property', key: 'power', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'givePart____NoPart', negated: false }],
        actions: [{ type: 'addCompletedMission', mission: 14 }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [{ type: 'addNewPart' }, { type: 'addCompletedMission', mission: 14 }],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with boat.power, givePart = #NoPart', () => {
    const ctx = createMockContext({ boatProperties: { power: true }, other: { givePart____NoPart: true } });
    const contract = new LingoContract('decompiled_lingo/71/71/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(14);
  });

  test('branch 2: with boat.power, givePart = #NoPart', () => {
    const ctx = createMockContext({ boatProperties: { power: true }, other: { givePart____NoPart: false } });
    const contract = new LingoContract('decompiled_lingo/71/71/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.partsAdded).toBeGreaterThan(0);
    expect(result.missionsCompleted).toContain(14);
  });

});
