/**
 * @fileoverview Behavioral parity tests for Lingo folder: 77
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 77.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 15.ls
// Pattern: inventory_check
describe('BehaviorScript 15.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'JustDoItPrimaBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 15.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('JustDoItPrimaBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 15.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 16.ls
// Pattern: inventory_check
describe('BehaviorScript 16.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'JustDoItDogBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 16.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('JustDoItDogBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 16.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 21.ls
// Pattern: inventory_check
describe('BehaviorScript 21.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'CantDoItDogBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 21.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('CantDoItDogBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 21.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 23.ls
// Pattern: inventory_check
describe('BehaviorScript 23.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'JustDoItBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 23.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('JustDoItBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 23.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 24.ls
// Pattern: inventory_check
describe('BehaviorScript 24.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'JustDoItBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 24.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('JustDoItBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 24.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 25.ls
// Pattern: simple_transition
describe('BehaviorScript 25.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'notrip' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 25.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('notrip');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 26.ls
// Pattern: prima_trip
describe('BehaviorScript 26.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'primaTrip', target: 'gDir' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 26.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.primaTrip).toBe(true);
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 27.ls
// Pattern: simple_transition
describe('BehaviorScript 27.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'trip' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 27.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('trip');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 28.ls
// Pattern: simple_transition
describe('BehaviorScript 28.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'trip' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 28.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('trip');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 3.ls
// Pattern: simple_transition
describe('BehaviorScript 3.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 3.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 31.ls
// Pattern: inventory_check
describe('BehaviorScript 31.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'SCJustDoItPrimaBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 31.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('SCJustDoItPrimaBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 31.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 32.ls
// Pattern: inventory_check
describe('BehaviorScript 32.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'SCcantDoItPrimaBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 32.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('SCcantDoItPrimaBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 32.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 33.ls
// Pattern: inventory_check
describe('BehaviorScript 33.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'cantDoItPrimaBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 33.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('cantDoItPrimaBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 33.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 34.ls
// Pattern: inventory_check
describe('BehaviorScript 34.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
      actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }, { type: 'go', target: 'DeliverMapBag' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 34.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
    expect(result.transition).toBe('DeliverMapBag');
  });

  test('branch 2: without DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 34.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 36.ls
// Pattern: simple_transition
describe('BehaviorScript 36.ls → beginSprite', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'the_deliverMap_of_gDir___1', negated: false }],
      actions: [{ type: 'go', target: 'deliverMapRing' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: the deliverMap of gDir = 1', () => {
    const ctx = createMockContext({ other: { the_deliverMap_of_gDir___1: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 36.ls', 'beginSprite', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('deliverMapRing');
  });

  test('branch 2: the deliverMap of gDir = 1', () => {
    const ctx = createMockContext({ other: { the_deliverMap_of_gDir___1: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 36.ls', 'beginSprite', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/BehaviorScript 4.ls
// Pattern: simple_transition
describe('BehaviorScript 4.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'ringleave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/BehaviorScript 4.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('ringleave');
  });

});

// Source: decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: complex_branching
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'objId', negated: false }],
      actions: [{ type: 'goVar', var: 'myMarker' }, { type: 'setInInventory', item: 'Belly' }],
      children: [
      {
        conditions: [{ type: 'inventory', key: 'DoctorBag', negated: false }],
        actions: [{ type: 'setInInventory', item: 'Pills' }, { type: 'addCompletedMission', mission: 3 }],
        children: [],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'inventory', key: 'Swimring', negated: false }],
        actions: [{ type: 'addNewPart' }, { type: 'deleteFromInventory', item: 'Swimring' }, { type: 'addCompletedMission', mission: 2 }],
        children: [],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: 'tmpStartSuffix___VOID', negated: false }],
        actions: [],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      },
      {
        conditions: [{ type: 'missionGiven', key: '22', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'inventory', key: 'MapPiece1', negated: true }],
          actions: [{ type: 'setInInventory', item: 'MapPiece1' }, { type: 'addCompletedMission', mission: 22 }],
          children: [],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'missionGiven', key: '5', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'property', key: 'LuxuryFactor', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'medal', key: '8', negated: true }],
            actions: [{ type: 'addMedal', medal: 6 }],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'missionGiven', key: '5', negated: true }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'missionGiven', key: '4', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'property', key: 'Doghouse', negated: false }],
            actions: [{ type: 'addGivenMission', mission: 5 }, { type: 'setInInventory', item: 'Blinddog' }],
            children: [],
            elseBranch:             {
              conditions: [],
              actions: [],
              children: [],
              elseBranch: null,
            },
          }
        ],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'missionCompleted', key: '5', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'tmpRing___1', negated: false }],
          actions: [],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [
            {
              conditions: [{ type: 'property', key: 'LuxuryFactor', negated: false }],
              actions: [],
              children: [
              {
                conditions: [{ type: 'medal', key: '6', negated: true }],
                actions: [{ type: 'addMedal', medal: 6 }],
                children: [],
                elseBranch:                 {
                  conditions: [],
                  actions: [],
                  children: [],
                  elseBranch: null,
                },
              }
            ],
              elseBranch:               {
                conditions: [],
                actions: [],
                children: [],
                elseBranch: null,
              },
            }
          ],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
      {
        conditions: [{ type: 'other', key: 'tmpStartSuffix____BagNoRing_', negated: false }],
        actions: [{ type: 'deleteFromInventory', item: 'DoctorBag' }],
        children: [],
        elseBranch: null,
      }
    ],
      elseBranch: null,
    }
  ];

  test('branch 1: objId, with DoctorBag', () => {
    const ctx = createMockContext({ inventory: { DoctorBag: true }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('Pills');
    expect(result.missionsCompleted).toContain(3);
  });

  test('branch 2: objId, with Swimring', () => {
    const ctx = createMockContext({ inventory: { Swimring: true }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.partsAdded).toBeGreaterThan(0);
    expect(result.inventoryDeleted).toContain('Swimring');
    expect(result.missionsCompleted).toContain(2);
  });

  test('branch 3: objId, mission 22 given, without MapPiece1', () => {
    const ctx = createMockContext({ inventory: { MapPiece1: false }, missionsGiven: { '22': true }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('MapPiece1');
    expect(result.missionsCompleted).toContain(22);
  });

  test('branch 4: objId, mission 5 given, with boat.LuxuryFactor, no medal 8', () => {
    const ctx = createMockContext({ boatProperties: { LuxuryFactor: true }, medals: { '8': false }, missionsGiven: { '5': true }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.medalsAdded).toContain(6);
  });

  test('branch 5: objId, mission 5 not given, mission 4 given, with boat.Doghouse', () => {
    const ctx = createMockContext({ boatProperties: { Doghouse: true }, missionsGiven: { '4': true, '5': false }, other: { objId: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsGiven).toContain(5);
    expect(result.inventorySet).toContain('Blinddog');
  });

  test('branch 6: objId, mission 5 completed, tmpRing = 1, with boat.LuxuryFactor, no medal 6', () => {
    const ctx = createMockContext({ boatProperties: { LuxuryFactor: true }, medals: { '6': false }, missionsCompleted: { '5': true }, other: { objId: true, tmpRing___1: false } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.medalsAdded).toContain(6);
  });

  test('branch 7: objId, tmpStartSuffix = "BagNoRing"', () => {
    const ctx = createMockContext({ other: { objId: true, tmpStartSuffix____BagNoRing_: true } });
    const contract = new LingoContract('decompiled_lingo/77/77/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventoryDeleted).toContain('DoctorBag');
  });

});
