/**
 * @fileoverview Behavioral parity tests for Lingo folder: 79
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 79.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/79/79/casts/Internal/BehaviorScript 15.ls
// Pattern: simple_transition
describe('BehaviorScript 15.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'justDoIt' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/BehaviorScript 15.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('justDoIt');
  });

});

// Source: decompiled_lingo/79/79/casts/Internal/BehaviorScript 2.ls
// Pattern: simple_transition
describe('BehaviorScript 2.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/BehaviorScript 2.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/79/79/casts/Internal/BehaviorScript 28.ls
// Pattern: simple_transition
describe('BehaviorScript 28.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'justDoIt' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/BehaviorScript 28.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('justDoIt');
  });

});

// Source: decompiled_lingo/79/79/casts/Internal/BehaviorScript 3.ls
// Pattern: simple_transition
describe('BehaviorScript 3.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'cantDoIt' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/BehaviorScript 3.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('cantDoIt');
  });

});

// Source: decompiled_lingo/79/79/casts/Internal/BehaviorScript 5.ls
// Pattern: simple_transition
describe('BehaviorScript 5.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'anchorleave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/BehaviorScript 5.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('anchorleave');
  });

});

// Source: decompiled_lingo/79/79/casts/Internal/BehaviorScript 9.ls
// Pattern: simple_transition
describe('BehaviorScript 9.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'burkLeave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/BehaviorScript 9.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('burkLeave');
  });

});

// Source: decompiled_lingo/79/79/casts/Internal/ParentScript 4 - Dir.ls
// Pattern: inventory_check
describe('ParentScript 4 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'objId', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'inventory', key: 'tmpStuffNeeded', negated: false }],
      actions: [{ type: 'addCompletedMission', mission: 17 }, { type: 'deleteFromInventory', item: 'tmpStuffNeeded' }, { type: 'setInInventory', item: 'Belly' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with tmpStuffNeeded', () => {
    const ctx = createMockContext({ inventory: { tmpStuffNeeded: true } });
    const contract = new LingoContract('decompiled_lingo/79/79/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(17);
    expect(result.inventoryDeleted).toContain('tmpStuffNeeded');
    expect(result.inventorySet).toContain('Belly');
  });

});
