/**
 * @fileoverview Behavioral parity tests for Lingo folder: 81
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 81.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/81/81/casts/Internal/BehaviorScript 2.ls
// Pattern: simple_transition
describe('BehaviorScript 2.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/81/81/casts/Internal/BehaviorScript 2.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/81/81/casts/Internal/BehaviorScript 6.ls
// Pattern: simple_transition
describe('BehaviorScript 6.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/81/81/casts/Internal/BehaviorScript 6.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/81/81/casts/Internal/ParentScript 4 - Dir.ls
// Pattern: inventory_check
describe('ParentScript 4 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'inventory', key: 'RottenFish', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'tmpCapacity____rottenFishWeight', negated: false }],
          actions: [{ type: 'addCompletedMission', mission: 9 }, { type: 'setInInventory', item: 'RottenFish' }],
          children: [
          {
            conditions: [{ type: 'other', key: 'rottenFishWeight____35', negated: false }],
            actions: [{ type: 'addMedal', medal: 3 }],
            children: [],
            elseBranch: null,
          }
        ],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: without RottenFish, tmpCapacity >= rottenFishWeight, rottenFishWeight >= 35', () => {
    const ctx = createMockContext({ inventory: { RottenFish: false }, other: { rottenFishWeight____35: true, tmpCapacity____rottenFishWeight: true } });
    const contract = new LingoContract('decompiled_lingo/81/81/casts/Internal/ParentScript 4 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.medalsAdded).toContain(3);
  });

});
