/**
 * @fileoverview Behavioral parity tests for Lingo folder: 84
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 84.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/84/84/casts/Internal/BehaviorScript 10.ls
// Pattern: simple_transition
describe('BehaviorScript 10.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/BehaviorScript 10.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/84/84/casts/Internal/BehaviorScript 14.ls
// Pattern: simple_transition
describe('BehaviorScript 14.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [{ type: 'property', key: 'Watertank', negated: false }],
      actions: [{ type: 'addCompletedMission', mission: 11 }, { type: 'go', target: 'justdoItTank' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goFramePlus', offset: 1 }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with boat.Watertank', () => {
    const ctx = createMockContext({ boatProperties: { Watertank: true } });
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/BehaviorScript 14.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(11);
    expect(result.transition).toBe('justdoItTank');
  });

  test('branch 2: without boat.Watertank', () => {
    const ctx = createMockContext({ boatProperties: { Watertank: false } });
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/BehaviorScript 14.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('frame+1');
  });

});

// Source: decompiled_lingo/84/84/casts/Internal/BehaviorScript 2.ls
// Pattern: simple_transition
describe('BehaviorScript 2.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/BehaviorScript 2.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/84/84/casts/Internal/BehaviorScript 26.ls
// Pattern: simple_transition
describe('BehaviorScript 26.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'justDoittank' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/BehaviorScript 26.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('justDoittank');
  });

});

// Source: decompiled_lingo/84/84/casts/Internal/ParentScript 3 - Dir.ls
// Pattern: mission_check
describe('ParentScript 3 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionCompleted', key: '11', negated: true }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'property', key: 'Watertank', negated: false }],
        actions: [{ type: 'addCompletedMission', mission: 11 }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'missionCompleted', key: '21', negated: true }],
      actions: [{ type: 'addCompletedMission', mission: 21 }, { type: 'addNewPart' }, { type: 'addGivenMission', mission: 11 }],
      children: [
      {
        conditions: [{ type: 'property', key: 'Watertank', negated: false }],
        actions: [{ type: 'addCompletedMission', mission: 11 }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'property', key: 'CombineHarvester', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'missionCompleted', key: '10', negated: true }],
        actions: [{ type: 'addCompletedMission', mission: 10 }, { type: 'setInInventory', item: 'helmet' }],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'other', key: 'myMarker___VOID', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: mission 11 not completed, with boat.Watertank', () => {
    const ctx = createMockContext({ boatProperties: { Watertank: true }, missionsCompleted: { '11': false } });
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/ParentScript 3 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(11);
  });

  test('branch 2: mission 21 not completed, with boat.Watertank', () => {
    const ctx = createMockContext({ boatProperties: { Watertank: true }, missionsCompleted: { '21': false } });
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/ParentScript 3 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(11);
  });

  test('branch 3: with boat.CombineHarvester, mission 10 not completed', () => {
    const ctx = createMockContext({ boatProperties: { CombineHarvester: true }, missionsCompleted: { '10': false } });
    const contract = new LingoContract('decompiled_lingo/84/84/casts/Internal/ParentScript 3 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.missionsCompleted).toContain(10);
    expect(result.inventorySet).toContain('helmet');
  });

});
