/**
 * @fileoverview Behavioral parity tests for Lingo folder: 86
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 86.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/86/86/casts/Internal/BehaviorScript 20.ls
// Pattern: simple_transition
describe('BehaviorScript 20.ls → exitFrame', () => {
  const branches = [
    {
      conditions: [],
      actions: [{ type: 'go', target: 'leave' }],
      children: [],
      elseBranch: null,
    }
  ];

  test('branch 1: default state', () => {
    const ctx = createMockContext({});
    const contract = new LingoContract('decompiled_lingo/86/86/casts/Internal/BehaviorScript 20.ls', 'exitFrame', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('leave');
  });

});

// Source: decompiled_lingo/86/86/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: complex_branching
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionGiven', key: '8', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [
        {
          conditions: [{ type: 'missionCompleted', key: '8', negated: true }],
          actions: [{ type: 'setInInventory', item: 'MapPiece3' }, { type: 'addGivenMission', mission: 8 }],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'missionCompleted', key: '4', negated: false }],
      actions: [],
      children: [],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'missionCompleted', key: '8', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'missionCompleted', key: '4', negated: false }],
        actions: [],
        children: [],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [
          {
            conditions: [{ type: 'missionGiven', key: '4', negated: false }],
            actions: [],
            children: [
            {
              conditions: [{ type: 'inventory', key: 'Blinddog', negated: false }],
              actions: [{ type: 'addCompletedMission', mission: 4 }, { type: 'deleteFromInventory', item: 'Blinddog' }, { type: 'addGivenMission', mission: 10 }],
              children: [
              {
                conditions: [{ type: 'other', key: 'gotPart_the_user_of_gMulleGlobals__975__', negated: true }],
                actions: [{ type: 'addNewPart' }],
                children: [],
                elseBranch: null,
              }
            ],
              elseBranch:               {
                conditions: [],
                actions: [],
                children: [],
                elseBranch: null,
              },
            }
          ],
            elseBranch: null,
          }
        ],
          elseBranch: null,
        },
      }
    ],
      elseBranch: null,
    },
    {
      conditions: [{ type: 'medal', key: '1', negated: true }],
      actions: [{ type: 'addMedal', medal: 1 }, { type: 'go', target: 'medalStart' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'goVar', var: 'myMarker' }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: mission 8 not given, mission 8 not completed', () => {
    const ctx = createMockContext({ missionsCompleted: { '8': false }, missionsGiven: { '8': false } });
    const contract = new LingoContract('decompiled_lingo/86/86/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.inventorySet).toContain('MapPiece3');
    expect(result.missionsGiven).toContain(8);
  });

  test('branch 2: mission 8 completed, mission 4 not completed, mission 4 given, with Blinddog, gotPart(the user of gMulleGlobals, 975) = 0', () => {
    const ctx = createMockContext({ inventory: { Blinddog: true }, missionsCompleted: { '4': false, '8': true }, missionsGiven: { '4': true }, other: { gotPart_the_user_of_gMulleGlobals__975__: false } });
    const contract = new LingoContract('decompiled_lingo/86/86/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.partsAdded).toBeGreaterThan(0);
  });

  test('branch 3: no medal 1', () => {
    const ctx = createMockContext({ medals: { '1': false } });
    const contract = new LingoContract('decompiled_lingo/86/86/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.medalsAdded).toContain(1);
    expect(result.transition).toBe('medalStart');
  });

  test('branch 4: has medal 1', () => {
    const ctx = createMockContext({ medals: { '1': true } });
    const contract = new LingoContract('decompiled_lingo/86/86/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:myMarker');
  });

});
