/**
 * @fileoverview Behavioral parity tests for Lingo folder: 87
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene 87.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/87/87/casts/Internal/ParentScript 1 - Dir.ls
// Pattern: inventory_check
describe('ParentScript 1 - Dir.ls → startMovie', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'objectp_the_world_of_gMulleGlobals_', negated: false }],
      actions: [],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'inventory', key: 'helmet', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'inventory', key: 'Suit', negated: false }],
        actions: [{ type: 'addCompletedMission', mission: 12 }, { type: 'addMedal', medal: 5 }],
        children: [
        {
          conditions: [{ type: 'other', key: 'gotPart_the_user_of_gMulleGlobals__979__', negated: true }],
          actions: [{ type: 'addNewPart' }],
          children: [],
          elseBranch:           {
            conditions: [],
            actions: [],
            children: [],
            elseBranch: null,
          },
        }
      ],
        elseBranch:         {
          conditions: [],
          actions: [],
          children: [],
          elseBranch: null,
        },
      }
    ],
      elseBranch:       {
        conditions: [],
        actions: [],
        children: [],
        elseBranch: null,
      },
    },
    {
      conditions: [{ type: 'other', key: 'getCompletedMissionInfo_the_user_of_gMul', negated: false }],
      actions: [{ type: 'goVar', var: 'myMarker' }],
      children: [],
      elseBranch:       {
        conditions: [],
        actions: [{ type: 'go', target: 'start' }],
        children: [],
        elseBranch: null,
      },
    }
  ];

  test('branch 1: with helmet, with Suit, gotPart(the user of gMulleGlobals, 979) = 0', () => {
    const ctx = createMockContext({ inventory: { Suit: true, helmet: true }, other: { gotPart_the_user_of_gMulleGlobals__979__: false } });
    const contract = new LingoContract('decompiled_lingo/87/87/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.partsAdded).toBeGreaterThan(0);
  });

  test('branch 2: getCompletedMissionInfo(the user of gMulleGlobals,', () => {
    const ctx = createMockContext({ other: { getCompletedMissionInfo_the_user_of_gMul: true } });
    const contract = new LingoContract('decompiled_lingo/87/87/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:myMarker');
  });

  test('branch 3: getCompletedMissionInfo(the user of gMulleGlobals,', () => {
    const ctx = createMockContext({ other: { getCompletedMissionInfo_the_user_of_gMul: false } });
    const contract = new LingoContract('decompiled_lingo/87/87/casts/Internal/ParentScript 1 - Dir.ls', 'startMovie', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('start');
  });

});
