/**
 * @fileoverview Behavioral parity tests for Lingo folder: shared_00
 * Auto-generated by generate_behavioral_tests.py
 *
 * These tests verify that the JS remake branches match the original
 * Lingo conditional logic for scene shared_00.
 */

const { LingoContract, createMockContext } = require('./helpers');

// Source: decompiled_lingo/shared_00/00/casts/External/ParentScript 21 - MouseObject.ls
// Pattern: simple_transition
describe('ParentScript 21 - MouseObject.ls → mouse', () => {
  const branches = [
    {
      conditions: [{ type: 'other', key: 'listp_optionList_', negated: false }],
      actions: [],
      children: [
      {
        conditions: [{ type: 'other', key: 'listp_actionList_', negated: false }],
        actions: [],
        children: [
        {
          conditions: [{ type: 'other', key: 'count_actionList____0', negated: false }],
          actions: [],
          children: [
          {
            conditions: [{ type: 'other', key: 'not__voidp_eventPic__or_voidp_SP__', negated: true }],
            actions: [],
            children: [
            {
              conditions: [{ type: 'other', key: 'the_loc_of_sprite_SP___point_0__0_', negated: false }],
              actions: [],
              children: [],
              elseBranch: null,
            }
          ],
            elseBranch: null,
          },
          {
            conditions: [{ type: 'other', key: 'not__voidp_eventSound__or_soundBusy_2__o', negated: true }],
            actions: [],
            children: [],
            elseBranch: null,
          },
          {
            conditions: [{ type: 'other', key: 'not_voidp_eventFrame_', negated: true }],
            actions: [{ type: 'goVar', var: 'eventFrame' }],
            children: [],
            elseBranch: null,
          },
          {
            conditions: [{ type: 'other', key: 'not_voidp_eventStopSound__and__soundID__', negated: true }],
            actions: [],
            children: [],
            elseBranch: null,
          },
          {
            conditions: [{ type: 'other', key: 'not_voidp_eventInsideCheck_', negated: true }],
            actions: [],
            children: [],
            elseBranch: null,
          }
        ],
          elseBranch: null,
        }
      ],
        elseBranch: null,
      }
    ],
      elseBranch: null,
    }
  ];

  test('branch 1: listp(optionList), listp(actionList), count(actionList) > 0, not voidp(eventFrame)', () => {
    const ctx = createMockContext({ other: { count_actionList____0: true, listp_actionList_: true, listp_optionList_: true, not_voidp_eventFrame_: false } });
    const contract = new LingoContract('decompiled_lingo/shared_00/00/casts/External/ParentScript 21 - MouseObject.ls', 'mouse', branches);
    const result = contract.evaluate(ctx);
    expect(result.transition).toBe('var:eventFrame');
  });

});
